Some improvement based on China's interviewers' feedback.
techops-recsys-lateral-hiring/frontend-developer-joyofenergy pull request #5
Opened 2021-06-22 09:33 UTC by DeruiDENG

2021-07-03 15:53 UTC, gabrielmccallin-tw requested changes
NICE ONE DeruiDENG! 👍

Can we discuss the use of the `onload` listener? The use of a `module` type is there as a interview conversation starter - esmodules having finally become the de facto module pattern.

2021-07-03 15:53 UTC, gabrielmccallin-tw commented on README.md
> +You can create *.ts files or import it into any of the existing files.
I think we should mention that this is provided by Snowpack and that there is no build step at the moment.

2021-07-03 15:53 UTC, gabrielmccallin-tw commented on chart.js
> +let chart = null;
This is so we can reuse the chart instead of recreating it? If so can we just do

`let chart;`

I'm not a fan of `null`

2021-07-03 15:53 UTC, gabrielmccallin-tw commented on index.css
> +  font-family: "Nunito";
YES! ❤️ this idea

2021-07-03 15:53 UTC, gabrielmccallin-tw commented on index.js
> +window.onload = async () => {
Why the `onload` listener? The script tag in `index.html` is of type `module` so it loads and runs it with module magic ✨. 

Am I missing something?

2021-07-03 15:53 UTC, gabrielmccallin-tw commented on reading.js
> +export const getReadings = async (length = 1200) => {
Does this need to be `async`?

2021-07-03 15:53 UTC, gabrielmccallin-tw commented on package.json
> +    "node": "^14.16.1"
Yep, good call

2021-07-03 15:53 UTC, gabrielmccallin-tw commented on package.json
> +    "prettier": "^2.3.1",
This is a good idea and might provoke some conversations in the interview. 

Can we also add a lint fix script? I think like this:

```
"format-fix": "prettier -w ./*.js",
"format": "prettier  -c ./*.js"

```

2021-07-05 08:43 UTC, DeruiDENG commented on reading.js
> +export const getReadings = async (length = 1200) => {
In the real scenarios, getReadings should get the reading from a backend server, which should be async logic.
Even though we are using mock data, I still think we should use the async function in here, which also address the concern that we don't have the opportunity to test the candidates' async programming skills.

2021-07-05 08:47 UTC, DeruiDENG commented on chart.js
> +let chart = null;
I am fine on both options.
I can do the change.

2021-07-05 08:56 UTC, DeruiDENG commented on README.md
> +You can create *.ts files or import it into any of the existing files.
I feel we don't need to mention that we don't need the build command, because actually `snowpack build` is required if we want to deploy the app to production.(https://www.snowpack.dev/concepts/build-pipeline)

Providing `snowpack start` alone shouldn't be confusing to the candidates, because popular framework/buildtools like create-react-app, nextjs, webpack all support similar commands which can start the dev-server.

2021-07-05 09:08 UTC, DeruiDENG commented on index.js
> +window.onload = async () => {
Since the module type script is deferred by default, it may not make sense to use an onload listener anymore(even though deferred script will still run before the onload event)
Good callout and I will remove this.

2021-07-05 09:40 UTC, DeruiDENG commented
Hey @gabrielmccallin-tw  
Thanks for your feedback, I have made some changes, please review again. If you got more questions/concerns, please msg me directly.

2021-07-06 12:20 UTC, gabrielmccallin-tw commented
Great points @DeruiDENG! 
Let's MERGE! 🚀

2021-07-06 12:20 UTC, gabrielmccallin-tw approved these changes

2021-07-13 06:13 UTC, merged